<a href="https://colab.research.google.com/github/baikAnalyst/BigDataAnalyticsEngineer_Test/blob/main/20231014_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# numpy array type and shape

a1 = np.array([1, 2, 3])
print(a1)
print('array1 type: ', type(a1))
print('array1 shape : ', a1.shape)
print()

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print('array2 type : ', type(a2))
print('array2 shape : ', a2.shape)
print()

a3 = np.array([[1, 2, 3]])
print(a3)
print('array3 type : ', type(a3))
print('array3 shape : ', a3.shape)


[1 2 3]
array1 type:  <class 'numpy.ndarray'>
array1 shape :  (3,)

[[1 2 3]
 [4 5 6]]
array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)

[[1 2 3]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)


In [6]:
# dimension

print('array1 dim : ', a1.ndim)
print('array2 dim : ', a2.ndim)
print('array3 dim : ', a3.ndim)

array1 dim :  1
array2 dim :  2
array3 dim :  2


https://velog.io/@jhdai_ly/%EB%84%98%ED%8C%8C%EC%9D%B4Numpyn%EC%B0%A8%EC%9B%90-%EB%B0%B0%EC%97%B4-%EA%B0%9C%EB%85%90-%EC%83%9D%EC%84%B11-ndarray-shape-ndim-size-dtype <br>
n차원 배열에 대한 기본 개념입니다.<br>
처음 배열부터 차례대로 1차원, 2차원, 3차원 배열이라고 부르며<br>
1차원 배열 - axis(축) : 0으로 구성 / Vector라고 부름<br>
2차원 배열 - axis(축) : 0, 1로 구성 / Matrix라고 부름(행렬)<br>
3차원 배열 - axis(축) : 0, 1, 2로 구성 / Tensor라고 부름<br>
<br>
https://pybasall.tistory.com/129<br>
## 축 개념 이해하기<br>



배열에 대한 생각을 바꿔봅시다. 배열은 단지 리스트의 중첩입니다. 축은 단지 가장 바깥 리스트에서 안쪽리스트 순으로 0부터 이름을 붙인 것입니다.



예를들어



[[1,2,3],[4,5,6]]



라는 배열이 있다고 합시다.



axis0 은 [1,2,3]->[4,5,6] 로 진행되는 방향입니다.  (행)

axis1 은 1->2->3 또는 4->5->6으로 진행되는 방향입니다. (열)



axis0을 행방향(위->아래), axis1을 열방항(좌->우)로 해석할 수도 있지만 굳이 그러지 않아도 상관 없습니다.



차원을 하나 높여봅시다.



[ [[1,2],
   [3,4]] ,
  [[5,6],
   [7,8]] ]



axis0은 [[1,2],[3,4]] -> [[5,6],[7,8]]로 진행되는 방향입니다.  (가장 바깥쪽 리스트의 요소: 차원 Z축)

axis1은 [1,2] -> [3,4] 또는 [5,6] -> [7,8]로 진행되는 방향입니다. (그보다는 안쪽 리스트의 요소: 행 y축)

axis2는 1->2 또는 3->4 또는 5->6 또는 7->8로 진행되는 방향입니다. (가장 안쪽 리스트의 요소: 열 x축)



이런 방식으로 이해한다면 차원이 4차원 이상 높아져도 축 개념을 잡을 수 있습니다. 일종의 축의 '추상화'인것이죠. 행렬개념으로 이해할 경우 4차원 이상에서 축개념을 잡을 수가 없습니다.
<br><br>
https://steadiness-193.tistory.com/50
<br><br>
여기가 설명 맛집인듯...<br>
https://hyeonnii.tistory.com/328

In [7]:
# arange

a = np.arange(20)  # start 0, end 20-1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
a = np.arange(1, 20, 3)  # start, end, step
print(a)

[ 1  4  7 10 13 16 19]


In [9]:
# zeros, ones

zero_a = np.zeros((2,5))
one_a = np.ones((3,4))

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# zeros_like

zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# ones_like

one_b = np.ones_like(zero_a)
print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# full, random

full_a = np.full((4,3),9)
random_a = np.random.random((3,4))

print(full_a)
print(random_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.12392841 0.72393985 0.22082188 0.91982324]
 [0.94630901 0.42904321 0.29847998 0.50125165]
 [0.46528211 0.48733285 0.76233614 0.40903066]]


In [13]:
# eye

eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# reshape -1

array1 = np.arange(12)
print('array1:\n', array1)

array2 = array1.reshape(3,4)
print('array2:\n', array2)

array3 = array1.reshape(3,4, order='F') # f 열 우선 변경, c
print('array3:\n', array3)

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [17]:
# reshape -2

array1 = np.arange(10)
array2 = array1.reshape(-1, 5) # 행을 알아서 맞춰주고 열은 5개

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)



[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dim :  2
array2 shape :  (2, 5)


In [19]:
# reshape -3

array1 = np.arange(12)
array2 = array1.reshape(2,3,2, order='F') # f컬럼우선 변경, c행 우선변경

print(array1)
print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
array2 dim :  3
array2 shape :  (2, 3, 2)


In [20]:
# flatten :  reshaping  to 1dim

array3 = array2.flatten()
print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


In [22]:

# single value extraction from 1dim array (similar to pandas indexing)
array1 = np.arange(1, 10)
print('array1 : ', array1)

value1 = array1[2]
value2 = array1[-2]

print(value1)
print(value2)

array1 :  [1 2 3 4 5 6 7 8 9]
3
8


In [28]:
# single value extraction from muliti-dim array

array1 = np.arange(1, 10)
array2 = array1.reshape(3,3)
print('array2:\n', array2)

vaule1 = array2[0, 0]    # 1이어야 하는데 왜 3일까...결국 1을 받아냈음 ㅎ
value2 = array2[-1, -1] # 9
value3 = array2[-1, -2] # 8

print(value1)
print(value2)
print(value3)

print(array2[0, 0])

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8
1


In [29]:
# 1 dim array slicing

array1 = np.arange(1, 10)     # [1 2 3 4 5 6 7 8 9] # no comma in numpy array
array2 = array1[0:3]             # [1 2 3]
array3 = array1[:3]               # [1 2 3]
array4 = array1[3:]               # [4 5 6 7 8 9]

print(type(array2))
print(array2)
print(array3)
print(array4)

<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


In [31]:
# multi dim array slicing

array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

print('array2[0:2, 0:2]\n', array2[0:2, 0:2])
print('array2[0:2, 0:2, 0:2]\n', array2[0:2, 0:2, 0:2])

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]]


IndexError: ignored

In [33]:
array1 = np.arange(1, 10) # *
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

print('array2[0:2, 0:2]\n', array2[0:2, 0:2])
print('array2[1:3, 0:3]\n', array2[1:3, 0:3])
print('array2[:2, 1:]\n', array2[:2, 1:])
print('array2[:2, 0]\n', array2[:2, 0])

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]]
array2[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2[:2, 1:]
 [[2 3]
 [5 6]]
array2[:2, 0]
 [1 4]


In [34]:
# matrix dot product
array1 = np.array([[1,2,3],
                            [4,5,6]])
array2 = np.array([[7,8],
                            [9,10],
                            [11,12] ])

dot_array = np.dot(array1, array2)
print(dot_array)

[[ 58  64]
 [139 154]]


In [35]:
# matrix transpose

array1 = np.array([[1,2,3],
                            [4,5,6]])

transpose_array = np.transpose(array1)

print(transpose_array)

[[1 4]
 [2 5]
 [3 6]]


In [36]:
# len(array)

x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
                     2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
len(x)


26

In [37]:
# mean, variance(mean of diff**2), standard deviation(variance**2)

print(np.mean(x))
print(np.var(x))
print(np.std(x))



4.8076923076923075
115.23224852071006
10.734628476137871


In [38]:
# max, min, median

print(np.max(x))
print(np.min(x))
print(np.median(x))

23
-24
5.0


In [39]:
# quartile
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))

0.0
5.0
10.0
